// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2SWd5Bp4HxDUggJed4O_YSJ-oItLIrI',
    appId: '1:336619668827:web:4d031f532b23f781ebc67e',
    messagingSenderId: '336619668827',
    projectId: 'brisull-lfl-flutterfile',
    authDomain: 'brisull-lfl-flutterfile.firebaseapp.com',
    storageBucket: 'brisull-lfl-flutterfile.appspot.com',
    measurementId: 'G-N0WZP380XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxaPr0ma6w-Fe3933ib7hQg_36Eaj6xoE',
    appId: '1:336619668827:android:ab23e149a38cb7c0ebc67e',
    messagingSenderId: '336619668827',
    projectId: 'brisull-lfl-flutterfile',
    storageBucket: 'brisull-lfl-flutterfile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtHRncE9kg2ZbGoAnDEVt4GkKkZBfzoME',
    appId: '1:336619668827:ios:f85f31e5c1a78ed1ebc67e',
    messagingSenderId: '336619668827',
    projectId: 'brisull-lfl-flutterfile',
    storageBucket: 'brisull-lfl-flutterfile.appspot.com',
    iosClientId:
        '336619668827-a57a0mq0imdqpfriabn1eo8rflkp5aks.apps.googleusercontent.com',
    iosBundleId: 'com.souvikbiswas.flutterfireExamples',
  );
}
